###########################################################
# 1) Dependencies stage
###########################################################
FROM node:20-alpine AS deps

# Set working directory
WORKDIR /app

# Install dependencies using npm
COPY package.json package-lock.json ./
RUN npm ci

###########################################################
# 2) Build stage
###########################################################
FROM node:20-alpine AS builder

WORKDIR /app

# Reuse node_modules from deps layer
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build Next.js (produces .next/standalone)
RUN npm run build

###########################################################
# 3) Runtime stage
###########################################################
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

# If you use next/image's built-in optimization, Next expects these:
ENV HOSTNAME=0.0.0.0

# Copy standalone server and static files
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

# server.js is generated by Next standalone build
CMD ["node", "server.js"]
